scripts/dtc: Fix multiple definition of yylloc
In GCC 10 -fcommon changed to -fno-common causing the following linker
error:

/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition
  of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here

Signed-off-by: Philip Molloy <philip@philipmolloy.com>